# 公共配置文件

server:
  port: 8123
  servlet:
    context-path: /api
yuapi:
  client:
    access-key: yupi
    secret-key: abcdefgh
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuapi
    username: root
    password: 123456

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848